package indicators

// CanonicalRegistry returns the complete dictionary of registered KPIs and metrics
// identified for Canadian national sovereign intelligence and project execution.
func CanonicalRegistry() []*KPIDefinition {
	return []*KPIDefinition{
		// -------------------------------------------------------------
		// Pillar 1: ESG & Decarbonization
		// -------------------------------------------------------------
		{
			Code:               KPIEmissionsIntensityScope12,
			Name:               "Scope 1 & 2 Emissions Intensity",
			Category:           CategoryESGDecarbonization,
			Description:        "Direct and indirect operational greenhouse gas emissions per $1M CAD capex or per tonne output.",
			Unit:               "tCO2e/$1M CAD",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    45.0,
			BenchmarkUnit:      "tCO2e/$1M CAD",
			BenchmarkLabel:     "Net-Zero 2050 Sectoral Pathway Threshold",
			StatutoryBasis:     "Canadian Net-Zero Emissions Accountability Act (S.C. 2021, c. 22)",
			Publisher:          "Environment and Climate Change Canada (ECCC) GHG Reporting",
			UpdateFrequency:    "ANNUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIEmissionsAbatementAnnual,
			Name:               "Annual Lifecycle GHG Abatement",
			Category:           CategoryESGDecarbonization,
			Description:        "Net greenhouse gas emissions avoided or sequestered annually relative to baseline fossil counter-factual.",
			Unit:               "Mt CO2e/yr",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    1.5,
			BenchmarkUnit:      "Mt CO2e/yr",
			BenchmarkLabel:     "Canada 2030 Emissions Reduction Plan Contributor",
			StatutoryBasis:     "Federal 2030 Emissions Reduction Plan (ERP)",
			Publisher:          "Clean Energy Canada / ECCC National Inventory",
			UpdateFrequency:    "ANNUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPICarbonTaxSensitivity,
			Name:               "OBPS Carbon Tax Exposure Sensitivity",
			Category:           CategoryESGDecarbonization,
			Description:        "Marginal annual project operating cost impact per $10/tonne escalation in Federal OBPS benchmark carbon price.",
			Unit:               "$CAD/tonne CO2e",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    170.0,
			BenchmarkUnit:      "$CAD/tonne",
			BenchmarkLabel:     "2030 Statutory Carbon Price Cap ($170/t)",
			StatutoryBasis:     "Greenhouse Gas Pollution Pricing Act (GGPPA)",
			Publisher:          "Department of Finance Canada / CRA",
			UpdateFrequency:    "ANNUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIWaterRecyclingRatio,
			Name:               "Industrial Water Circularity & Recycling Ratio",
			Category:           CategoryESGDecarbonization,
			Description:        "Percentage of operational process water recycled or closed-loop circulated on site.",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    85.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Best-in-Class Zero Liquid Discharge (ZLD) Standard",
			StatutoryBasis:     "Fisheries Act (Metal and Diamond Mining Effluent Regulations)",
			Publisher:          "ECCC Water Quality Monitoring",
			UpdateFrequency:    "QUARTERLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPICleanPowerPurityPct,
			Name:               "Clean Zero-Carbon Power Utilization Share",
			Category:           CategoryESGDecarbonization,
			Description:        "Percentage of connected electricity consumption supplied from zero-emitting generation (hydro, nuclear, wind, solar).",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    95.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Clean Electricity Regulations (CER) 2035 Compliance",
			StatutoryBasis:     "Federal Clean Electricity Regulations (CER)",
			Publisher:          "Provincial System Operators (IESO, AESO, HQ, BC Hydro)",
			UpdateFrequency:    "MONTHLY",
			IsLiveFeed:         false,
		},

		// -------------------------------------------------------------
		// Pillar 2: Indigenous Economic Sovereignty
		// -------------------------------------------------------------
		{
			Code:               KPIIndigenousEquityPct,
			Name:               "First Nations Equity Co-Ownership Stake",
			Category:           CategoryIndigenousEquity,
			Description:        "Percentage of project commercial equity owned by host First Nations, Inuit, or Métis communities.",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    25.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "CIB / National Indigenous Economic Strategy Target",
			StatutoryBasis:     "UNDRIP Act & TRC Call to Action 92",
			Publisher:          "Canada Infrastructure Bank (CIB) / First Nations Major Projects Coalition",
			UpdateFrequency:    "EVENT_DRIVEN",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIIndigenousProcurementShare,
			Name:               "Indigenous Enterprise Procurement Share",
			Category:           CategoryIndigenousEquity,
			Description:        "Percentage of Tier-1 and Tier-2 procurement contracts awarded to verified Indigenous-owned businesses.",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    10.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Exceeds Federal 5% Mandatory Baseline (PSPC Mandate)",
			StatutoryBasis:     "Directive on Government Contracts Awarded to Indigenous Businesses",
			Publisher:          "Indigenous Services Canada / CCAB Certified Aboriginal Businesses",
			UpdateFrequency:    "QUARTERLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIIndigenousWorkforcePct,
			Name:               "Local Indigenous Workforce Participation",
			Category:           CategoryIndigenousEquity,
			Description:        "Proportion of peak construction and steady-state operating workforce from host Indigenous communities.",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    20.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Northern Impact Benefit Agreement (IBA) Gold Standard",
			StatutoryBasis:     "Impact Benefit Agreements (IBAs) / Section 35 Consultations",
			Publisher:          "Statistics Canada Indigenous Peoples Survey & Project Disclosures",
			UpdateFrequency:    "ANNUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIIndigenousILGPGuaranteeCAD,
			Name:               "Indigenous Loan Guarantee Program Allocation",
			Category:           CategoryIndigenousEquity,
			Description:        "Federal debt guarantee allocated under the $5B Canada Indigenous Loan Guarantee Program.",
			Unit:               "CAD",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    100_000_000,
			BenchmarkUnit:      "CAD",
			BenchmarkLabel:     "$5B Federal Pool Allocation Capacity",
			StatutoryBasis:     "Budget 2024 / NRCan Indigenous Loan Guarantee Program",
			Publisher:          "Natural Resources Canada (NRCan) / Canada Development Investment Corp",
			UpdateFrequency:    "EVENT_DRIVEN",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIIndigenousCommunityDividend,
			Name:               "30-Year Annualized Community Dividend Yield",
			Category:           CategoryIndigenousEquity,
			Description:        "Net untied sovereign annual cash flow distributed to community trust accounts for intergenerational prosperity.",
			Unit:               "CAD/yr",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    12_000_000,
			BenchmarkUnit:      "CAD/yr",
			BenchmarkLabel:     "Sovereign Intergenerational Community Fund",
			StatutoryBasis:     "First Nations Fiscal Management Act",
			Publisher:          "First Nations Financial Management Board (FMB)",
			UpdateFrequency:    "ANNUAL",
			IsLiveFeed:         false,
		},

		// -------------------------------------------------------------
		// Pillar 3: Capital Spend Velocity & Hazards
		// -------------------------------------------------------------
		{
			Code:               KPICapexSpendVelocityCADMo,
			Name:               "Capital Deployment Spend Velocity",
			Category:           CategoryCapitalVelocity,
			Description:        "Average monthly capital deployment and procurement cash-out run-rate during active execution.",
			Unit:               "CAD_M/month",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    35.0,
			BenchmarkUnit:      "$M CAD/mo",
			BenchmarkLabel:     "Efficient Megaproject Spend Rate Baseline",
			StatutoryBasis:     "Major Projects Management Office (MPMO) Reporting",
			Publisher:          "Corporate Filings (SEDAR+) & Contractor Invoices",
			UpdateFrequency:    "MONTHLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIScheduleSlipMonths,
			Name:               "Cumulative Critical-Path Schedule Slip",
			Category:           CategoryCapitalVelocity,
			Description:        "Months variance between current forecasted commercial operation date (COD) and baseline Final Investment Decision (FID).",
			Unit:               "months",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    0.0,
			BenchmarkUnit:      "months",
			BenchmarkLabel:     "Zero-Slippage Critical Path Delivery",
			StatutoryBasis:     "Treasury Board Directive on the Management of Major Projects",
			Publisher:          "CEAO / Regulatory Filings / Independent Engineering Reports",
			UpdateFrequency:    "QUARTERLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPICostOverrunHazardPct,
			Name:               "Flyvbjerg Cost Overrun Hazard Probability",
			Category:           CategoryCapitalVelocity,
			Description:        "Empirical Bayesian lognormal probability of exceeding approved capital budget by >20%.",
			Unit:               "percent",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    25.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Low-Tail-Risk Benchmark (<25% Hazard)",
			StatutoryBasis:     "Infrastructure Canada Capital Risk Guidelines",
			Publisher:          "Oxford Megaproject Database / CEO-G Risk Engine",
			UpdateFrequency:    "CONTINUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIPublicCrowdingMultiplier,
			Name:               "Private Capital Crowding-In Multiplier",
			Category:           CategoryCapitalVelocity,
			Description:        "Ratio of private institutional capital mobilized per $1 CAD of federal/provincial concessionary debt or grant.",
			Unit:               "ratio_x",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    4.0,
			BenchmarkUnit:      "x",
			BenchmarkLabel:     "CIB Legislative Target (Minimum 3x-5x Private Crowding-In)",
			StatutoryBasis:     "Canada Infrastructure Bank Act (S.C. 2017, c. 20, s. 403)",
			Publisher:          "Canada Infrastructure Bank (CIB) Annual Reports",
			UpdateFrequency:    "EVENT_DRIVEN",
			IsLiveFeed:         false,
		},

		// -------------------------------------------------------------
		// Pillar 4: Sovereign Supply Chain & Domestic Content
		// -------------------------------------------------------------
		{
			Code:               KPIDomesticCanadianContentPct,
			Name:               "Canadian Domestic Content Share",
			Category:           CategorySupplyChainContent,
			Description:        "Proportion of direct capital expenditures and services procured from suppliers registered with a Canadian Business Number (BN).",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    70.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Bill C-59 Domestic Industrial Benefit Target",
			StatutoryBasis:     "Fall Economic Statement Implementation Act (Bill C-59)",
			Publisher:          "ISED Canadian Company Capabilities (CCC) & CRA BN Registry",
			UpdateFrequency:    "SEMI_ANNUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPICriticalBottleneckScore,
			Name:               "Critical Equipment Bottleneck & Lead-Time Index",
			Category:           CategorySupplyChainContent,
			Description:        "Composite risk rating (1-100) assessing global procurement queues for transformers, calandria, turbines, and specialized metallurgy.",
			Unit:               "score_1_to_100",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    30.0,
			BenchmarkUnit:      "points",
			BenchmarkLabel:     "Low Supply-Chain Disruption Risk (<30)",
			StatutoryBasis:     "National Supply Chain Strategy / Transport Canada",
			Publisher:          "Transport Canada Supply Chain Task Force & IMF PortWatch",
			UpdateFrequency:    "MONTHLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIUSTariffExposurePct,
			Name:               "U.S. Cross-Border Trade & Tariff Vulnerability",
			Category:           CategorySupplyChainContent,
			Description:        "Percentage of projected commercial offtake revenue subject to U.S. Section 232, Section 301, or border adjustment measures.",
			Unit:               "percent",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    15.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Diversified Global Trade Offtake Shield",
			StatutoryBasis:     "Canada-United States-Mexico Agreement (CUSMA / USMCA)",
			Publisher:          "Global Affairs Canada (GAC) Trade Controls Bureau",
			UpdateFrequency:    "QUARTERLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIDomesticImportReplacement,
			Name:               "Annual Domestic Import Replacement Value",
			Category:           CategorySupplyChainContent,
			Description:        "Estimated annual dollar value of foreign imports directly displaced by project output (e.g. refined battery chemicals, SMR power).",
			Unit:               "CAD_M/yr",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    250.0,
			BenchmarkUnit:      "$M CAD/yr",
			BenchmarkLabel:     "Major Sovereign Industrial Contribution",
			StatutoryBasis:     "Canadian Critical Minerals Strategy",
			Publisher:          "Statistics Canada Trade Data Online (TDO)",
			UpdateFrequency:    "ANNUAL",
			IsLiveFeed:         false,
		},

		// -------------------------------------------------------------
		// Pillar 5: Power, Grid Interconnection & Hosting
		// -------------------------------------------------------------
		{
			Code:               KPIPeakPowerDemandMW,
			Name:               "Connected Peak Electrical Demand / Generation",
			Category:           CategoryGridPhysics,
			Description:        "Total firm electrical load or dispatchable clean power capacity to be connected to the bulk electricity system.",
			Unit:               "MW",
			PreferredDirection: DirectionNeutral,
			TargetBenchmark:    300.0,
			BenchmarkUnit:      "MW",
			BenchmarkLabel:     "Transmission-Class Industrial Interconnection",
			StatutoryBasis:     "National Energy Board / Provincial Electricity Acts",
			Publisher:          "Provincial ISOs / CER",
			UpdateFrequency:    "EVENT_DRIVEN",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIGridInterconnectQueueMo,
			Name:               "Grid Interconnection Queue Wait Latency",
			Category:           CategoryGridPhysics,
			Description:        "Elapsed months from initial System Impact Assessment (SIA) filing to signed Interconnection Agreement.",
			Unit:               "months",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    18.0,
			BenchmarkUnit:      "months",
			BenchmarkLabel:     "Streamlined System Impact Assessment (SIA) Latency",
			StatutoryBasis:     "IESO / AESO Market Rules",
			Publisher:          "IESO / AESO / Hydro-Québec Transmission Queue Registries",
			UpdateFrequency:    "MONTHLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIGridHostingHeadroomMW,
			Name:               "Substation Electrical Hosting Headroom",
			Category:           CategoryGridPhysics,
			Description:        "Available unallocated transformation capacity at nearest transmission node prior to requiring system upgrades.",
			Unit:               "MW",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    150.0,
			BenchmarkUnit:      "MW",
			BenchmarkLabel:     "Sufficient Local Transformation Margin",
			StatutoryBasis:     "Ontario Energy Board Transmission System Code",
			Publisher:          "Hydro One / AltaLink / BC Hydro Transmission Planning",
			UpdateFrequency:    "QUARTERLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPISystemReinforcementCost,
			Name:               "Upstream Network Reinforcement Capital Cost",
			Category:           CategoryGridPhysics,
			Description:        "Required external capital allocation to reinforce regional 230kV/500kV bulk transmission lines and capacitor banks.",
			Unit:               "CAD",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    25_000_000,
			BenchmarkUnit:      "CAD",
			BenchmarkLabel:     "Minimal Network Reinforcement Burden",
			StatutoryBasis:     "Provincial Utility Rate Hearings",
			Publisher:          "Independent System Operator Connection Assessments",
			UpdateFrequency:    "EVENT_DRIVEN",
			IsLiveFeed:         false,
		},

		// -------------------------------------------------------------
		// Pillar 6: Regulatory, Permitting & Legal Latency
		// -------------------------------------------------------------
		{
			Code:               KPIIAACStatutoryDurationMo,
			Name:               "Federal Impact Assessment (IAAC) Elapsed Duration",
			Category:           CategoryRegulatorySpeed,
			Description:        "Cumulative elapsed months in federal environmental impact review from initial description to Ministerial Decision Statement.",
			Unit:               "months",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    24.0,
			BenchmarkUnit:      "months",
			BenchmarkLabel:     "Federal Impact Assessment Act 2-Year Target (Bill C-69 Reforms)",
			StatutoryBasis:     "Impact Assessment Act (S.C. 2019, c. 28, s. 1)",
			Publisher:          "Impact Assessment Agency of Canada (IAAC) Registry",
			UpdateFrequency:    "MONTHLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIPermitCompletionPct,
			Name:               "Statutory Permitting Completion Progress",
			Category:           CategoryRegulatorySpeed,
			Description:        "Percentage of required municipal, provincial water/mining, and federal approvals formally executed and in good standing.",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    90.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Construction-Ready Statutory Threshold",
			StatutoryBasis:     "Provincial Environmental Protection & Mining Acts",
			Publisher:          "Provincial EA Registries (BC EAO, ERO, AER)",
			UpdateFrequency:    "MONTHLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIJudicialReviewRiskIndex,
			Name:               "Litigious Friction & Judicial Review Risk Index",
			Category:           CategoryRegulatorySpeed,
			Description:        "Quantitative exposure score (1-100) assessing probability of Section 35 constitutional challenges or injunction filings.",
			Unit:               "score_1_to_100",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    20.0,
			BenchmarkUnit:      "points",
			BenchmarkLabel:     "Low Judicial Injunction Risk (<20)",
			StatutoryBasis:     "Constitution Act, 1982, Section 35",
			Publisher:          "Federal Court of Canada / LexisNexis Regulatory Registry",
			UpdateFrequency:    "CONTINUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIConditionsCount,
			Name:               "Legally Binding Environmental Certificate Conditions",
			Category:           CategoryRegulatorySpeed,
			Description:        "Total count of legally enforceable conditions attached to Environmental Assessment Approval Certificate.",
			Unit:               "count",
			PreferredDirection: DirectionNeutral,
			TargetBenchmark:    65.0,
			BenchmarkUnit:      "conditions",
			BenchmarkLabel:     "Manageable Compliance Envelope",
			StatutoryBasis:     "IAAC Decision Statement Terms & Conditions",
			Publisher:          "IAAC / BC EAO / Ontario Ministry of the Environment",
			UpdateFrequency:    "EVENT_DRIVEN",
			IsLiveFeed:         false,
		},

		// -------------------------------------------------------------
		// Pillar 7: Labour Dynamics & Critical Skills Pipeline
		// -------------------------------------------------------------
		{
			Code:               KPIRedSealTradesGap,
			Name:               "Peak Construction Red Seal Trades Deficit",
			Category:           CategoryLaborSkills,
			Description:        "Estimated regional shortfall of certified union journeypersons (electricians, pipefitters, boilermakers, millwrights) at peak construction.",
			Unit:               "FTE",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    0.0,
			BenchmarkUnit:      "FTE",
			BenchmarkLabel:     "Fully Balanced Craft Labour Supply",
			StatutoryBasis:     "Red Seal Program / Employment and Social Development Canada",
			Publisher:          "BuildForce Canada / Canadian Building Trades Unions (CBTU)",
			UpdateFrequency:    "ANNUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIApprenticeJourneyRatio,
			Name:               "Apprentice-to-Journeyperson Ratio",
			Category:           CategoryLaborSkills,
			Description:        "Proportion of hours worked on job sites by registered apprentices (Bill C-59 ITC prevailing wage bonus compliance: minimum 10%).",
			Unit:               "percent",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    12.0,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Bill C-59 Clean Economy ITC Bonus Threshold (>=10%)",
			StatutoryBasis:     "Income Tax Act s. 127.44 (Labour Requirements for Clean Economy ITCs)",
			Publisher:          "Canada Revenue Agency (CRA) / Provincial Apprenticeship Boards",
			UpdateFrequency:    "QUARTERLY",
			IsLiveFeed:         false,
		},
		{
			Code:               KPIHousingAbsorptionDeficit,
			Name:               "Local Municipality Housing Absorption Deficit",
			Category:           CategoryLaborSkills,
			Description:        "Shortfall of temporary or permanent housing units within 45 minutes travel radius to accommodate inbound construction crews without displacement.",
			Unit:               "units",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    0.0,
			BenchmarkUnit:      "units",
			BenchmarkLabel:     "Adequate Municipal Rental Headroom",
			StatutoryBasis:     "National Housing Strategy Act",
			Publisher:          "Canada Mortgage and Housing Corporation (CMHC)",
			UpdateFrequency:    "SEMI_ANNUAL",
			IsLiveFeed:         false,
		},
		{
			Code:               KPITotalPersonYearsCreated,
			Name:               "Total Lifecycle Person-Years Created",
			Category:           CategoryLaborSkills,
			Description:        "Combined direct, indirect supply chain, and induced consumer spending employment created over construction and operations.",
			Unit:               "person_years",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    8_500.0,
			BenchmarkUnit:      "person_years",
			BenchmarkLabel:     "Major Employment Driver",
			StatutoryBasis:     "Statistics Canada Input-Output Multipliers",
			Publisher:          "Statistics Canada SUT Model & Project Filings",
			UpdateFrequency:    "EVENT_DRIVEN",
			IsLiveFeed:         false,
		},

		// -------------------------------------------------------------
		// Pillar 8: Live Commodity & Macro Benchmark Feeds
		// -------------------------------------------------------------
		{
			Code:               KPIWCSWTIDifferential,
			Name:               "Western Canadian Select (WCS) - WTI Crude Discount",
			Category:           CategoryCommodityMacro,
			Description:        "Heavy crude pricing differential at Hardisty, Alberta relative to Cushing WTI benchmark.",
			Unit:               "USD/bbl",
			PreferredDirection: DirectionLowerBetter,
			TargetBenchmark:    12.50,
			BenchmarkUnit:      "USD/bbl",
			BenchmarkLabel:     "Narrow Discount Baseline (<$13.00)",
			StatutoryBasis:     "Canada Energy Regulator (CER) Commodity Pricing",
			Publisher:          "ICE Crude Futures / Argus Media / CER",
			UpdateFrequency:    "REALTIME",
			IsLiveFeed:         true,
		},
		{
			Code:               KPIAECOGasSpotCAD,
			Name:               "AECO C Natural Gas Spot Price",
			Category:           CategoryCommodityMacro,
			Description:        "Western Canadian benchmark natural gas hub price at NIT Nova Inventory Transfer.",
			Unit:               "CAD/GJ",
			PreferredDirection: DirectionNeutral,
			TargetBenchmark:    2.75,
			BenchmarkUnit:      "CAD/GJ",
			BenchmarkLabel:     "Economic Feedstock Parity",
			StatutoryBasis:     "Alberta Utilities Commission (AUC) / CER",
			Publisher:          "NGX (Natural Gas Exchange) / CER",
			UpdateFrequency:    "DAILY",
			IsLiveFeed:         true,
		},
		{
			Code:               KPILMENickelCashUSD,
			Name:               "LME Grade-1 Nickel Cash Settlement Price",
			Category:           CategoryCommodityMacro,
			Description:        "London Metal Exchange cash contract for 99.80% purity primary nickel for battery cathode offtake.",
			Unit:               "USD/tonne",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    18_500.0,
			BenchmarkUnit:      "USD/t",
			BenchmarkLabel:     "Canadian SMR & EV Mine Breakeven ($17.5k-$19k)",
			StatutoryBasis:     "Canadian Critical Minerals Strategy Offtake Benchmarks",
			Publisher:          "London Metal Exchange (LME) / S&P Platts",
			UpdateFrequency:    "REALTIME",
			IsLiveFeed:         true,
		},
		{
			Code:               KPIUraniumUXU3O8USD,
			Name:               "Ux U3O8 Spot Uranium Price",
			Category:           CategoryCommodityMacro,
			Description:        "Industry benchmark spot price per pound of triuranium octoxide yellowcake for Canadian CANDU/SMR reactor fuel.",
			Unit:               "USD/lb",
			PreferredDirection: DirectionNeutral,
			TargetBenchmark:    85.0,
			BenchmarkUnit:      "USD/lb",
			BenchmarkLabel:     "Stable Long-Term Fuel Cycle Window ($75-$95)",
			StatutoryBasis:     "Nuclear Safety and Control Act",
			Publisher:          "UxC Weekly Spot Indicator / Cameco Indices",
			UpdateFrequency:    "WEEKLY",
			IsLiveFeed:         true,
		},
		{
			Code:               KPILithiumCarbonateUSD,
			Name:               "Battery-Grade Lithium Carbonate (99.5% Li2CO3)",
			Category:           CategoryCommodityMacro,
			Description:        "Spot benchmark for North American / European delivered battery precursor lithium carbonate.",
			Unit:               "USD/tonne",
			PreferredDirection: DirectionHigherBetter,
			TargetBenchmark:    14_000.0,
			BenchmarkUnit:      "USD/t",
			BenchmarkLabel:     "Commercial Extraction Incentive Threshold",
			StatutoryBasis:     "Federal Critical Minerals Infrastructure Fund",
			Publisher:          "Fastmarkets / Benchmark Mineral Intelligence",
			UpdateFrequency:    "WEEKLY",
			IsLiveFeed:         true,
		},
		{
			Code:               KPICADUSDExchangeRate,
			Name:               "Bank of Canada CAD/USD Nominal Spot Exchange Rate",
			Category:           CategoryCommodityMacro,
			Description:        "Official Bank of Canada daily noon fixing for Canadian Dollar against U.S. Dollar.",
			Unit:               "CAD_per_USD",
			PreferredDirection: DirectionNeutral,
			TargetBenchmark:    0.735,
			BenchmarkUnit:      "USD_per_CAD",
			BenchmarkLabel:     "Monetary Neutral Range",
			StatutoryBasis:     "Bank of Canada Act (R.S.C., 1985, c. B-2)",
			Publisher:          "Bank of Canada Valet API",
			UpdateFrequency:    "BUSINESS_DAILY",
			IsLiveFeed:         true,
		},
		{
			Code:               KPIBoCOvernightRate,
			Name:               "Bank of Canada Policy Interest Rate (Overnight Target)",
			Category:           CategoryCommodityMacro,
			Description:        "Bank of Canada target for the overnight lending rate governing institutional debt facilities.",
			Unit:               "percent",
			PreferredDirection: DirectionNeutral,
			TargetBenchmark:    2.75,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Neutral Real Policy Rate",
			StatutoryBasis:     "Bank of Canada Monetary Policy Framework",
			Publisher:          "Bank of Canada Valet API",
			UpdateFrequency:    "FIXED_DATES",
			IsLiveFeed:         true,
		},
		{
			Code:               KPIGoC10YearBondYield,
			Name:               "Government of Canada 10-Year Benchmark Bond Yield",
			Category:           CategoryCommodityMacro,
			Description:        "Yield to maturity on 10-year GoC sovereign bonds serving as risk-free discount rate for Canadian project finance.",
			Unit:               "percent",
			PreferredDirection: DirectionNeutral,
			TargetBenchmark:    2.95,
			BenchmarkUnit:      "percent",
			BenchmarkLabel:     "Project Finance Hurdle Base",
			StatutoryBasis:     "Financial Administration Act",
			Publisher:          "Bank of Canada Valet API",
			UpdateFrequency:    "BUSINESS_DAILY",
			IsLiveFeed:         true,
		},
	}
}

// RegistryByCode returns a quick lookup map by KPICode.
func RegistryByCode() map[KPICode]*KPIDefinition {
	list := CanonicalRegistry()
	m := make(map[KPICode]*KPIDefinition, len(list))
	for _, def := range list {
		m[def.Code] = def
	}
	return m
}
