package domain

import "time"

// CapacityUnit represents the measurement unit for a project's production or
// throughput capacity. Typed units prevent accidental arithmetic across
// incompatible quantities (e.g., MW vs. tonnes/year).
type CapacityUnit string

const (
	UnitMW            CapacityUnit = "MW"
	UnitMWh           CapacityUnit = "MWh"
	UnitGW            CapacityUnit = "GW"
	UnitGWh           CapacityUnit = "GWh"
	UnitTonnesPerYear CapacityUnit = "TONNES_PER_YEAR"
	UnitMTPA          CapacityUnit = "MTPA"
	UnitKTPA          CapacityUnit = "KTPA"
	UnitBarrelsPerDay CapacityUnit = "BARRELS_PER_DAY"
	UnitMcfPerDay     CapacityUnit = "MCF_PER_DAY"
	UnitTEUPerYear    CapacityUnit = "TEU_PER_YEAR"
	UnitKilometres    CapacityUnit = "KM"
	UnitSquareMetres  CapacityUnit = "SQ_M"
	UnitSquareFeet    CapacityUnit = "SQ_FT"
	UnitAcres         CapacityUnit = "ACRES"
	UnitHectares      CapacityUnit = "HECTARES"
	UnitUnits         CapacityUnit = "UNITS"        // housing units, vehicles
	UnitOunces        CapacityUnit = "OZ"           // precious metals
	UnitCubicMetres   CapacityUnit = "CUBIC_METRES" // water, LNG
	UnitMWe           CapacityUnit = "MWe"          // electrical
	UnitMWt           CapacityUnit = "MWt"          // thermal
)

// CapacityType classifies the nature of the capacity measurement.
type CapacityType string

const (
	CapacityNameplate  CapacityType = "NAMEPLATE"
	CapacityPeak       CapacityType = "PEAK"
	CapacityNet        CapacityType = "NET"
	CapacityAnnual     CapacityType = "ANNUAL_PRODUCTION"
	CapacityDaily      CapacityType = "DAILY_PRODUCTION"
	CapacityStorage    CapacityType = "STORAGE"
	CapacityThroughput CapacityType = "THROUGHPUT"
	CapacityFloorArea  CapacityType = "FLOOR_AREA"
	CapacityLandArea   CapacityType = "LAND_AREA"
	CapacityReserve    CapacityType = "RESERVE"
	CapacityResource   CapacityType = "RESOURCE"
)

// CapacityStatus distinguishes planned targets from demonstrated output.
type CapacityStatus string

const (
	CapStatusPlanned     CapacityStatus = "PLANNED"
	CapStatusPermitted   CapacityStatus = "PERMITTED"
	CapStatusConstructed CapacityStatus = "CONSTRUCTED"
	CapStatusOperating   CapacityStatus = "OPERATING"
	CapStatusExpanded    CapacityStatus = "EXPANDED"
)

// CapacityMetric is a typed, evidence-linked measurement of project output or
// throughput. A single project may have multiple CapacityMetrics covering
// different units, phases, and measurement types.
type CapacityMetric struct {
	ID          string          `json:"id"`
	ProjectID   string          `json:"project_id"`
	PhaseID     string          `json:"phase_id,omitempty"`
	MetricType  CapacityType    `json:"metric_type"`
	Value       float64         `json:"value"`
	Unit        CapacityUnit    `json:"unit"`
	TimeBasis   string          `json:"time_basis,omitempty"` // "annual", "daily", "instantaneous"
	Status      CapacityStatus  `json:"status"`
	Confidence  ConfidenceLevel `json:"confidence"`
	EvidenceIDs []string        `json:"evidence_ids,omitempty"`
	Visibility  VisibilityClass `json:"visibility"`
	Publishable bool            `json:"publishable"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// EconomicOutputType classifies the nature of an economic output observation.
type EconomicOutputType string

const (
	OutputEmploymentDirect   EconomicOutputType = "EMPLOYMENT_DIRECT"
	OutputEmploymentIndirect EconomicOutputType = "EMPLOYMENT_INDIRECT"
	OutputConstructionJobs   EconomicOutputType = "CONSTRUCTION_JOBS"
	OutputGDPContribution    EconomicOutputType = "GDP_CONTRIBUTION_CAD"
	OutputTaxRevenue         EconomicOutputType = "TAX_REVENUE_CAD"
	OutputExportValue        EconomicOutputType = "EXPORT_VALUE_CAD"
	OutputLocalContent       EconomicOutputType = "LOCAL_CONTENT_PCT"
	OutputIndigenousBenefit  EconomicOutputType = "INDIGENOUS_BENEFIT_CAD"
)

// EconomicOutput records expected or observed socioeconomic impacts. These are
// projected/reported values linked to evidence, not projections generated by
// the system.
type EconomicOutput struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	PhaseID     string             `json:"phase_id,omitempty"`
	OutputType  EconomicOutputType `json:"output_type"`
	Value       float64            `json:"value"`
	Unit        string             `json:"unit"`
	Period      string             `json:"period,omitempty"` // "construction", "annual_operations", "lifetime"
	Status      ConfidenceLevel    `json:"status"`
	EvidenceIDs []string           `json:"evidence_ids,omitempty"`
	Visibility  VisibilityClass    `json:"visibility"`
	Publishable bool               `json:"publishable"`
	CreatedAt   time.Time          `json:"created_at"`
}
